# Generated by Django 4.1.7 on 2023-03-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
