# Generated by Django 4.1.7 on 2023-03-10 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0002_alter_itinerary_end_time_alter_itinerary_start_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TravelReason',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='reason',
            old_name='travel_reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='trip_reasons',
            new_name='reasons',
        ),
        migrations.RemoveField(
            model_name='tripreason',
            name='travel_reason',
        ),
        migrations.AddField(
            model_name='tripreason',
            name='reason',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_reason', to='passportapi.reason'),
            preserve_default=False,
        ),
    ]
