# Generated by Django 4.1.7 on 2023-03-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0003_rename_travelreason_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='itinerary_purposes',
        ),
        migrations.RemoveField(
            model_name='itinerarycategory',
            name='itinerary_category',
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='itinerary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='passportapi.itinerary'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItineraryPurpose',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='categories',
            field=models.ManyToManyField(through='passportapi.ItineraryCategory', to='passportapi.category'),
        ),
        migrations.AddField(
            model_name='itinerarycategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_categories', to='passportapi.category'),
            preserve_default=False,
        ),
    ]
