# Generated by Django 4.1.7 on 2023-03-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0004_category_remove_itinerary_itinerary_purposes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SitePhoto',
        ),
        migrations.RemoveField(
            model_name='itineraryphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tripphoto',
            name='user',
        ),
    ]
