# Generated by Django 4.1.7 on 2023-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0005_delete_sitephoto_remove_itineraryphoto_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='packed',
            field=models.BooleanField(default=False),
        ),
    ]
