# Generated by Django 4.1.7 on 2023-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0006_packinglist_packed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('-departure_date',)},
        ),
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
