# Generated by Django 4.1.7 on 2023-03-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0008_type_itinerary_public_trip_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('public', models.BooleanField(default=False)),
                ('itinerary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_product_itinerary', to='passportapi.itinerary')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_product_trip', to='passportapi.trip')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_product_type', to='passportapi.type')),
            ],
        ),
        migrations.CreateModel(
            name='StampPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('description', models.CharField(max_length=500)),
                ('public', models.BooleanField(default=False)),
                ('itinerary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_photo_itinerary', to='passportapi.itinerary')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_photo_trip', to='passportapi.trip')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_photo_type', to='passportapi.type')),
            ],
        ),
        migrations.CreateModel(
            name='StampJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entry', models.CharField(max_length=500)),
                ('public', models.BooleanField(default=False)),
                ('itinerary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_journal_itinerary', to='passportapi.itinerary')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_journal_trip', to='passportapi.trip')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stamp_journal_type', to='passportapi.type')),
            ],
        ),
    ]
