# Generated by Django 4.1.7 on 2023-03-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passportapi', '0010_stampjournal_date_created_stampphoto_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stampjournal',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='stampphoto',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterModelOptions(
            name='stampproduct',
            options={'ordering': ('-date_created',)},
        ),
    ]
